import type { Metadata } from 'next';
import Script from 'next/script';
import '../style/globals.css';
import { ToastContainer } from '@/components/common/toast';
import SessionProvider from '@/components/providers/session.provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className='h-dvh w-screen content-center'>
        <SessionProvider>
          <main className='relative mx-auto flex h-full max-h-dvh w-full min-w-[360px] max-w-[430px] flex-col bg-white'>
            {children}
          </main>
          <ToastContainer />
          <Script
            type='text/javascript'
            strategy='beforeInteractive'
            src={`https://dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_MAP_APP_KEY}&libraries=services&autoload=false`}
          />
        </SessionProvider>
      </body>
    </html>
  );
}
