import type { Metadata } from 'next';
import '../styles/globals.css';
import { AuthProvider } from '@/components/providers/auth.provider';
import QueryProvider from '@/components/providers/query.provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body>
        <AuthProvider>
          <QueryProvider>
            {children}
            <div id='modal-root' />
            <div id='toast-root' />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
